import type { Banner, Category, Product } from "@/types/product"

// Static categories data
export const staticCategories: Category[] = [
    {
        _id: "1",
        name: "Smartphones",
        slug: "smartphones",
        icon: "smartphone",
    },
    {
        _id: "2",
        name: "Headphones",
        slug: "headphones",
        icon: "headphones",
    },
    {
        _id: "3",
        name: "Laptops",
        slug: "laptops",
        icon: "laptop",
    },
    {
        _id: "4",
        name: "Accessories",
        slug: "accessories",
        icon: "package",
    },
]

// Static banners data
export const staticBanners: Banner[] = [
    {
        _id: "1",
        title: "Spring Sale",
        subtitle: "Up to 50% off",
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop",
        link: "/sale/spring",
        backgroundColor: "#A0522D",
        textColor: "#FFFFFF",
    },
    {
        _id: "2",
        title: "New Arrivals",
        subtitle: "Check out the latest styles",
        image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=2071&auto=format&fit=crop",
        link: "/new-arrivals",
        backgroundColor: "#1E3A8A",
        textColor: "#FFFFFF",
    },
    {
        _id: "3",
        title: "Summer Collection",
        subtitle: "Get ready for summer",
        image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=2070&auto=format&fit=crop",
        link: "/summer-collection",
        backgroundColor: "#10B981",
        textColor: "#FFFFFF",
    },
]

// Static products data
export const staticProducts: Product[] = [
    {
        _id: "1",
        title: "AirPods",
        description: "Wireless earbuds with premium sound quality.",
        slug: "airpods",
        category: staticCategories[1],
        price: 132.0,
        quantity: 50,
        images: [
            {
                name: "airpods_main",
                url: "https://images.unsplash.com/photo-1610438235354-a6ae5528385c?q=80&w=1974&auto=format&fit=crop",
            },
            {
                name: "airpods_alt",
                url: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?q=80&w=1943&auto=format&fit=crop",
            },
        ],
        brand: "Apple",
        sold: 120,
        isPublished: true,
        publishedAt: new Date("2023-01-15"),
        colors: ["white"],
        sizes: [],
        ratings: [
            { user: "user1", rating: 5 },
            { user: "user2", rating: 5 },
            { user: "user3", rating: 4 },
        ],
        createdAt: new Date("2023-01-01"),
        updatedAt: new Date("2023-01-15"),
        isNew: false,
        discountPercentage: 0,
        averageRating: 4.9,
    },
    {
        _id: "2",
        title: "MacBook Air 13",
        description: "Thin and light laptop with Apple M2 chip.",
        slug: "macbook-air-13",
        category: staticCategories[2],
        price: 1100.0,
        quantity: 30,
        images: [
            {
                name: "macbook_main",
                url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1926&auto=format&fit=crop",
            },
            {
                name: "macbook_alt",
                url: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=2070&auto=format&fit=crop",
            },
        ],
        brand: "Apple",
        sold: 85,
        isPublished: true,
        publishedAt: new Date("2023-02-10"),
        colors: ["silver", "space gray"],
        sizes: [],
        ratings: [
            { user: "user1", rating: 5 },
            { user: "user4", rating: 5 },
            { user: "user5", rating: 5 },
        ],
        createdAt: new Date("2023-02-01"),
        updatedAt: new Date("2023-02-10"),
        isNew: false,
        discountPercentage: 0,
        averageRating: 5.0,
    },
    {
        _id: "3",
        title: "iPhone 14 Pro",
        description: "Latest iPhone with advanced camera system.",
        slug: "iphone-14-pro",
        category: staticCategories[0],
        price: 999.0,
        quantity: 100,
        images: [
            {
                name: "iphone_main",
                url: "https://images.unsplash.com/photo-1678652197831-2d180705cd2c?q=80&w=1770&auto=format&fit=crop",
            },
            {
                name: "iphone_alt",
                url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=2574&auto=format&fit=crop",
            },
        ],
        brand: "Apple",
        sold: 150,
        isPublished: true,
        publishedAt: new Date("2023-03-05"),
        colors: ["black", "silver", "gold"],
        sizes: [],
        ratings: [
            { user: "user2", rating: 5 },
            { user: "user3", rating: 4 },
            { user: "user6", rating: 5 },
        ],
        createdAt: new Date("2023-03-01"),
        updatedAt: new Date("2023-03-05"),
        isNew: true,
        discountPercentage: 0,
        averageRating: 4.7,
    },
    {
        _id: "4",
        title: "iPad Pro",
        description: "Powerful tablet for professionals.",
        slug: "ipad-pro",
        category: staticCategories[0],
        price: 799.0,
        quantity: 45,
        images: [
            {
                name: "ipad_main",
                url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1975&auto=format&fit=crop",
            },
            {
                name: "ipad_alt",
                url: "https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?q=80&w=1974&auto=format&fit=crop",
            },
        ],
        brand: "Apple",
        sold: 70,
        isPublished: true,
        publishedAt: new Date("2023-04-20"),
        colors: ["space gray", "silver"],
        sizes: [],
        ratings: [
            { user: "user1", rating: 5 },
            { user: "user7", rating: 4 },
            { user: "user8", rating: 5 },
        ],
        createdAt: new Date("2023-04-01"),
        updatedAt: new Date("2023-04-20"),
        isNew: false,
        discountPercentage: 10,
        averageRating: 4.7,
    },
    {
        _id: "5",
        title: "Samsung Galaxy S23",
        description: "Premium Android smartphone with excellent camera.",
        slug: "samsung-galaxy-s23",
        category: staticCategories[0],
        price: 899.0,
        quantity: 60,
        images: [
            {
                name: "galaxy_main",
                url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=1771&auto=format&fit=crop",
            },
            {
                name: "galaxy_alt",
                url: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=1936&auto=format&fit=crop",
            },
        ],
        brand: "Samsung",
        sold: 90,
        isPublished: true,
        publishedAt: new Date("2023-05-15"),
        colors: ["black", "white", "green"],
        sizes: [],
        ratings: [
            { user: "user9", rating: 4 },
            { user: "user10", rating: 5 },
            { user: "user11", rating: 4 },
        ],
        createdAt: new Date("2023-05-01"),
        updatedAt: new Date("2023-05-15"),
        isNew: true,
        discountPercentage: 0,
        averageRating: 4.3,
    },
    {
        _id: "6",
        title: "Sony WH-1000XM5",
        description: "Premium noise-cancelling headphones.",
        slug: "sony-wh-1000xm5",
        category: staticCategories[1],
        price: 349.99,
        quantity: 40,
        images: [
            {
                name: "sony_main",
                url: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=1888&auto=format&fit=crop",
            },
            {
                name: "sony_alt",
                url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1932&auto=format&fit=crop",
            },
        ],
        brand: "Sony",
        sold: 60,
        isPublished: true,
        publishedAt: new Date("2023-06-10"),
        colors: ["black", "silver"],
        sizes: [],
        ratings: [
            { user: "user12", rating: 5 },
            { user: "user13", rating: 5 },
            { user: "user14", rating: 4 },
        ],
        createdAt: new Date("2023-06-01"),
        updatedAt: new Date("2023-06-10"),
        isNew: false,
        discountPercentage: 15,
        averageRating: 4.7,
    },
    {
        _id: "7",
        title: "Dell XPS 13",
        description: "Compact and powerful Windows laptop.",
        slug: "dell-xps-13",
        category: staticCategories[2],
        price: 1299.99,
        quantity: 25,
        images: [
            {
                name: "dell_main",
                url: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1932&auto=format&fit=crop",
            },
            {
                name: "dell_alt",
                url: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1770&auto=format&fit=crop",
            },
        ],
        brand: "Dell",
        sold: 40,
        isPublished: true,
        publishedAt: new Date("2023-07-05"),
        colors: ["silver"],
        sizes: [],
        ratings: [
            { user: "user15", rating: 4 },
            { user: "user16", rating: 5 },
            { user: "user17", rating: 4 },
        ],
        createdAt: new Date("2023-07-01"),
        updatedAt: new Date("2023-07-05"),
        isNew: false,
        discountPercentage: 0,
        averageRating: 4.3,
    },
    {
        _id: "8",
        title: "Apple Watch Series 8",
        description: "Advanced smartwatch with health features.",
        slug: "apple-watch-series-8",
        category: staticCategories[3],
        price: 399.0,
        quantity: 55,
        images: [
            {
                name: "watch_main",
                url: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=1772&auto=format&fit=crop",
            },
            {
                name: "watch_alt",
                url: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1964&auto=format&fit=crop",
            },
        ],
        brand: "Apple",
        sold: 80,
        isPublished: true,
        publishedAt: new Date("2023-08-15"),
        colors: ["black", "silver", "gold"],
        sizes: ["40mm", "44mm"],
        ratings: [
            { user: "user18", rating: 5 },
            { user: "user19", rating: 5 },
            { user: "user20", rating: 4 },
        ],
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-08-15"),
        isNew: true,
        discountPercentage: 0,
        averageRating: 4.7,
    },
]

// Popular products (sorted by sold count)
export const staticPopularProducts = [...staticProducts].sort((a, b) => b.sold - a.sold).slice(0, 4)

