import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import AppBar from "@/components/app-bar";
import ProtectedRoute from "@/components/protected-route";
import AuthProvider from "@/components/auth-provider";
import { Toaster } from "@/components/ui/toaster";
import { NavigationLoadingProvider } from "@/components/navigation-loading";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased , overflow-x-hidden`}
      >
        <AuthProvider>
          <ProtectedRoute>
            <SidebarProvider>
              <NavigationLoadingProvider>
                <AppSidebar />
                <SidebarInset className="bg-gray-100">
                  <AppBar />
                  {children}

                  <Toaster />
                </SidebarInset>
              </NavigationLoadingProvider>
            </SidebarProvider>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
